site_name: PyBotNet
site_description: PyBotNet framework, high level remote control 

theme:
  name: 'material'
  palette:
    - scheme: default
      primary: 'red'
      accent: 'red'
      toggle:
          icon: material/weather-sunny
          name: Switch to dark mode
    - scheme: slate
      primary: 'red'
      accent: 'red'
      toggle:
          icon: material/weather-night
          name: Switch to light mode

  favicon: 'favicon.png'
  features:
    - navigation.instant
    - navigation.top
    - navigation.sections
    - search.suggest
    - search.highlight
    - content.code.annotate

repo_name: onionj/pybotnet
repo_url: https://github.com/onionj/pybotnet

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - attr_list
  - tables
  - def_list

plugins:
  - search

nav:
  - About : index.md
  - Tutorial - User Guide:
    - tutorial_user_guide/tutorial_user_guide_intro.md


  - Advanced User Guide:
    - tutorial_advanced_guide/tutorial_advanced_guide_intro.md